### ISSUE TITLE
QA_Thermal Lens Spectroscopy by High Repetition Rate Femtosecond Lasers_Functionality_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#1]
Defect Description :
In the home page of the “Thermal Lens Spectroscopy by High Repetition Rate Femtosecond Lasers” experiment , the images are not displaying on the screen instead the images should be clearly visible to the user

Actual Result :
In the home page of the “Thermal Lens Spectroscopy by High Repetition Rate Femtosecond Lasers” experiment , the images are not displaying on the screen 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Thermal%20Lens%20Spectroscopy%20with%20High%20Repetition%20Rate%20Lasers/Thermal%20Lens%20Spectroscopy%20with%20High%20Repetition%20Rate%20Lasers_02_Functionality_smk.org

Attachment:
![uf1](https://cloud.githubusercontent.com/assets/14869397/15009056/ee2a3a98-1201-11e6-83ef-d0021261fc21.png)

**Comment by umraodhananjay** [comment]
Corrected Images URLs for all images
