### ISSUE TITLE
QA_Optical Tweezer with Femtosecond Laser Pulses_Image_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#2]
Defect Description :
When we click on the image displayed in the "Optical Tweezer with Femtosecond Laser Pulses" experiment home page , it is not redirecting to a new tab, where it should redirect to a new tab and the selected image should be displayed don the screen.

Actual Result :
When we click on the image displayed in the "Optical Tweezer with Femtosecond Laser Pulses" experiment home page , it is not redirecting to a new tab 

Environment  :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Optical%20Tweezer%20with%20Femtosecond%20Laser%20Pulses/Optical%20Tweezer%20with%20Femtosecond%20Laser%20Pulses_03_Image_p1.org

Attachment:
![uf2](https://cloud.githubusercontent.com/assets/14869397/15009046/d5d9618a-1201-11e6-85e7-7c21ab5093c8.png)

**Comment by umraodhananjay** [comment]
Created Redirecting Link For All the Images.........
