### ISSUE TITLE
QA_Live Cell Multiphoton Imaging: Principles & Experiments_Image_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#3]
Defect Description :
When we click on the image displayed in the "Live Cell Multiphoton Imaging: Principles & Experiments" experiment home page , it is not redirecting to a new tab, where it should redirect to a new tab and the selected image should be displayed don the screen.

Actual Result :
When we click on the image displayed in the "Live Cell Multiphoton Imaging: Principles & Experiments" experiment home page , it is not redirecting to a new tab  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Live%20Cell%20Multiphoton%20Imaging%20Principles%20%26%20Experiments/Live%20Cell%20Multiphoton%20Imaging%20Principles%20%26%20Experiments_03_Image_p1.org

Attachment:
![uf3](https://cloud.githubusercontent.com/assets/14869397/15009017/b609d7a4-1201-11e6-90c3-e4b15734fe50.png)

**Comment by umraodhananjay** [comment]
Created Redirection Link for new Tab of Image....
