### ISSUE TITLE
QA_Confocal Microscopy: Principles & Experiments_Referred_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#4]
Defect Description :
When we click on the referred link present in the "Confocal Microscopy: Principles & Experiments" experiment page , it is redirecting an error page(404) instead it should redirect to the referred page

Actual Result :
When we click on the referred link present in the "Confocal Microscopy: Principles & Experiments" experiment page , it is redirecting an error page(404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Confocal%20Microscopy%20Principles%20%26%20Experiments/Confocal%20Microscopy%20Principles%20%26%20Experiments_03_Referred_smk.org

Attachment:
![uf4](https://cloud.githubusercontent.com/assets/14869397/15009000/a2867746-1201-11e6-9b91-1cb51c577490.png)

**Comment by umraodhananjay** [comment]
We Have Correct Remove Refference Link........
