### ISSUE TITLE
QA_Confocal Microscopy: Principles & Experiments_Functionality_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#5]
Defect Description :
In the home page of the "Confocal Microscopy: Principles & Experiments" experiment , the images are not displaying on the screen instead the images should be clearly visible to the user

Actual Result :
In the home page of the "Confocal Microscopy: Principles & Experiments" experiment , the images are not displaying on the screen  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Confocal%20Microscopy%20Principles%20%26%20Experiments/Confocal%20Microscopy%20Principles%20%26%20Experiments_02_Functionality_smk.org

**Comment by umraodhananjay** [comment]
We Have Correct Image URLs.......
