### ISSUE TITLE
QA_Measure of Time-frequency bandwidth relation: Experimental demonstration of Heisenberg Uncertainity Principle_Functionality_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#6]
Defect Description :
In the home page of the   "Measure of Time-frequency bandwidth relation: Experimental demonstration of Heisenberg Uncertainty Principle" experiment , the images are not displaying on the screen instead the images should be clearly visible to the user

Actual Result :
In the home page of the   "Measure of Time-frequency bandwidth relation: Experimental demonstration of Heisenberg Uncertainty Principle" experiment , the images are not displaying on the screen  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5"

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Measure%20of%20Time-frequency%20bandwidth/Measure%20of%20Time-frequency%20bandwidth_02_Functionality_smk.org

Attachment:
![uf6](https://cloud.githubusercontent.com/assets/14869397/15008965/6873c2e8-1201-11e6-9ad8-09529642936c.png)

**Comment by umraodhananjay** [comment]
We Have Correct Image URLs.......
