### ISSUE TITLE
QA_Ultrafast Laser Pulse Measurement_Functionality_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/ultra-fast-laser-spectroscopy-iitk#7]
Defect Description :
In the home page of the   "Ultrafast Laser Pulse Measurement" experiment , the images are not displaying on the screen instead the images should be clearly visible to the user

Actual Result :
In the home page of the   "Ultrafast Laser Pulse Measurement" experiment , the images are not displaying on the screen 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/ultra-fast-laser-spectroscopy-iitk/blob/master/test-cases/integration_test-cases/Ultrafast%20Laser%20Pulse%20Measurment/Ultrafast%20Laser%20Pulse%20Measurment_02_Functionality_smk.org

Attachment:
![uf7](https://cloud.githubusercontent.com/assets/14869397/15008950/4825a812-1201-11e6-83ce-6be6bae5597a.png)

**Comment by umraodhananjay** [comment]
We have correct the Image URLs...........
